server:
  port: 8080

spring:
  application:
    name: auction-application-response-success
  datasource:
    username: 'postgres'
    url: jdbc:postgresql://localhost:5432/auctions
    password: 'root'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: true


