server:
  port: 8080

spring:
  application:
    name: auction-application-response-success
  datasource:
    driver-class-name: org.postgresql.Driver
    username: CHANGE_ME
    url: CHANGE_ME
    password: CHANGE_ME
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: true


